
server:
  port: 8000



spring:

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/${DB_NAME}?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=CTT
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate.hbm2ddl.auto: update
    open-in-view: false

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:

  session:
    store-type: none

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8



mybatis:
  configuration:
    map-underscore-to-camel-case: true



